// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srdbleufislvlisxqqnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyZGJsZXVmaXNsdmxpc3hxcW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0Nzg4NDMsImV4cCI6MjA2MTA1NDg0M30.e_aKIDm4ZooJ5IKPVW60X1qyDGXQajrXEatCP6VwGJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);